### PR TITLE
Add support for tool jolicode/castor

### PR DESCRIPTION
**Pull request by pyrech**
## A Pull Request should be associated with a Discussion.

> If you're fixing a bug, adding a new feature or improving something please provide the details in discussions,
> so that the development can be pointed in the intended direction.

Related discussion: https://github.com/shivammathur/setup-php/discussions/745

> Further notes in [Contribution Guidelines](.github/CONTRIBUTING.md)
> Thank you for your contribution.

### Description

This PR add support for the tool jolicode/castor.

A demo repository is provided here: https://github.com/pyrech/castor-setup-php (see [this run](https://github.com/pyrech/castor-setup-php/actions/runs/5357609301/jobs/9718707236?pr=1) for a working demo with my fork)

- [x] I have written test cases for the changes in this pull request
- [x] I have run `npm run format` before the commit.
- [x] I have run `npm run lint` before the commit.
- [x] I have run `npm run release` before the commit.
- [x] `npm test` returns with no unit test errors and all code covered.

### CODE REVIEW

**Comment by lyrixx** [comment]
That's so cool. Thanks

@shivammathur do you know when you will release it? (No pressure, I'm just asking)

**Comment by shivammathur** [comment]
@pyrech @lyrixx 
I will try to create a release next week.

A couple of issues I noticed, 
It does not print the version when running `castor -V` when using phar builds.
On Windows, it gets stuck when the action tries to run `castor -V`

**Comment by lyrixx** [comment]
Thanks for the feedback. we'll look at it

**Comment by pyrech** [comment]
Looks like the `-V` flag works when testing on my demo builds (on ubuntu-latest): https://github.com/pyrech/castor-setup-php/pull/1/checks

image

Do you have a reproducer?

**Comment by shivammathur** [comment]
@pyrech @lyrixx 
My bad. I did not copy the castor.php file to the directory I was testing in, After adding the file it is working correctly.

**Comment by pyrech** [comment]
Awesome, good to know. Yes, I think we could improve Castor behavior when no initial castor.php have been created yet.

Thanks

**Comment by lyrixx** [comment]
Hello,

For your information, the -V flag has been fixed, even if no castor.php file exist
Thanks for the report

And do you know when you'll be able to release a new version? Thanks 💛

**Comment by shivammathur** [comment]
@pyrech @lyrixx 
Sorry for the delay in the release. I was really busy with work at my job.

Released in [`2.25.5`](https://github.com/shivammathur/setup-php/releases/tag/2.25.5)

**Comment by pyrech** [comment]
No worries, that's awesome, thanks for the release 🎉

**Pull request merged**
