### PR TITLE
⚙ Document how to specify multiple extensions

### PR DESCRIPTION
**Pull request by spawnia**
I looked through the README and could not find any example of how to do it.

### CODE REVIEW

**Comment by shivammathur** [comment]
Hi @spawnia,
This is mentioned here https://github.com/shivammathur/setup-php#extensions-optional
Also, In my opinion it would be better to update the existing examples in Extension Support to illustrate this.

**Comment by spawnia** [comment]
Alright. It is really up to you, but I still think that my example does have value. The navigation led me to this section of the docs and I expected to find all relevant information about extensions there.

**Comment by shivammathur** [comment]
Updated [Extension Support](https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support) section.

**Comment by spawnia** [comment]
Nicely done, even better than my suggestion. Thank you

**Pull request closed without merging**
