### PR TITLE
🎉 Add blackfire extenstion

### LINKED ISSUE #191: Blackfire php-ext support
I would like to simplify the setup of my workflow that is using blackfire.io to profile my libraries. And since I'm already using this nice project to setup PHP in my workflow it would be very nice if we could add Blackfire as a supported extension. 

The Blackfire extension is supported on Windows, Linux, and OSX, so it could be part of this package to support the installation. I would understand if you are denying this request because Blackfire is a commercial product that is not free to use.

If you would accept this as a PR I will start implementing the installation on all operating systems with the required scripts.

### PR DESCRIPTION
**Pull request by jaapio**
This PR adds blackfire to all operating systems with php 5.6+ 

- [x] Readme updated
- [x] Linux install tested
- [ ] Windows install tested
- [x] Osx install tested

> In case this PR introduced TypeScript/JavaScript code changes:

- [x] I have written test cases for the changes in this pull request
- [x] I have run `npm run format` before the commit.
- [x] I have run `npm run lint` before the commit.
- [x] I have run `npm run release` before the commit.
- [x] `npm test` returns with no unit test errors.

Fixes #191

### CODE REVIEW

**Comment by jaapio** [comment]
@shivammathur could you please have a look at the windows support of the installation? I'm not familiar with the powershell scripting and I don't have a windows machine available to test the installation. So it would require a lot of trial and error for me to get this working. I think the script should work as is now.

**Comment by shivammathur** [comment]
@jaapio Great work 🎉. Please squash the commits into a single commit or one commit per OS. I will merge this and refactor/fix if required.

**Comment by jaapio** [comment]
I think it is ready now. Windows support is still failing. That would require some attention. But this is all I can do right now. Please let me know if I need to fix/update something before you can merge this.

**Comment by shivammathur** [comment]
Please remove blackfire from the workflow, so that builds pass. I will merge this now and later fix the windows script.

**Comment by jaapio** [comment]
I dropped the commit.

**Pull request merged**
