### PR TITLE
Simplify win32 script

### PR DESCRIPTION
**Pull request by mlocati**
---
name: ⚙ Simplify win32 script
about: The win32 script is overly complex: let's simplify it
labels: enhancement

---

Related issue: #85

- [X] I have written test cases for the changes in this pull request
- [X] I have run `npm run format` before the commit.
- [X] `npm test` returns with no unit test errors.

### CODE REVIEW

**Comment by mlocati** [comment]
I don't understand why the Prettier Format Check fails... On my PC it's passing:

image

**Comment by mlocati** [comment]
> I don't understand why the Prettier Format Check fails... On my PC it's passing:

Whoops, I didn't pushed the commit after running `npm run format`.

**Comment by shivammathur** [comment]
@mlocati Thanks.
Please check the changes with 7.4, `xdebug` fails to install and has to be manually downloaded from the website. Also, `Update-PhpCAInfo` is giving an error.

Here is a test run with your PR - https://github.com/shivammathur/test-setup-php/runs/319213043#step:3:1

**Comment by mlocati** [comment]
> Please check the changes with 7.4, `xdebug` fails to install and has to be manually downloaded from the website

Since version 1.19.0.224, PhpManager is able to download pre-release versions of xdebug (see https://github.com/mlocati/powershell-phpmanager/commit/aa98c1b2ed3cc41d77da973728c0ef9fffdddff3), but you have to state that you really want a pre-release version. So 71c631cffbd2369754f9a44df81205380a6c6be5 should be enough.

> Also, `Update-PhpCAInfo` is giving an error.

That's really strange: I'll check what's going wrong.

**Comment by shivammathur** [comment]
> So 71c631c should be enough.
`Xdebug` now fails to install on all versions
7.3 - https://github.com/shivammathur/test-setup-php/runs/319342116#step:3:26
7.4 - https://github.com/shivammathur/test-setup-php/runs/319342169#step:3:26

Stable PHP versions should have latest stable version of `Xdebug`. Also There is no `dll` for `Xdebug` on PECL for 7.4, that is why is fails, it is there on the website.

**Comment by shivammathur** [comment]
`Update-PhpCAInfo` error is now fixed. 👍

**Comment by mlocati** [comment]
I should have fixed all the issues. The only remaining issue is about the unused `version` variable in `addExtensionWindows`. Should I remove it?

**Comment by mlocati** [comment]
PS: IMHO function arguments should be excluded from the unused variables checks: we may not use them today, but we may require them tomorrow...

**Comment by shivammathur** [comment]
> PS: IMHO function arguments should be excluded from the unused variables checks: we may not use them today, but we may require them tomorrow...

I agree.

The tests are fine now. I will merge this.

**Comment by shivammathur** [comment]
Fixes #85

**Pull request merged**
