### PR TITLE
Tools: add PHPUnit Polyfills

### LINKED ISSUE #502: Tools: add support for PHPUnit Polyfills
**Describe the feature**
Would be great if the PHPUnit Polyfills Composer package would be available straight from tools.

Ref: https://github.com/Yoast/PHPUnit-Polyfills

**Note**: PHPUnit Polyfills has a (Composer) dependency on PHPUnit, but once installed, tests can be run both via Composer as well as via a PHPUnit PHAR file.
I'm not sure whether that would add extra complexity to an implementation for this ?

**Full disclosure**: I'm the author of the PHPUnit Polyfills package.

The package was released end of October last year and has reached (nearly) one million downloads already, so the uptake of projects using it is extensive (and still growing).

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
This tool is typically used to make test suites cross-version compatible with multiple PHPUnit versions.

**Are you willing to submit a PR?**
Yes, happy to, if you are open to adding the tool.

### PR DESCRIPTION
**Pull request by jrfnl**
---
name: 🎉 New Feature
about: Add a new feature
labels: enhancement
---

## A Pull Request should be associated with a Discussion.

Fixes #502 

### Description

This PR adds support for the [PHPUnit Polyfills](https://github.com/Yoast/PHPUnit-Polyfills) tool via the `tools` input to setup-php.

I have added a test to the `linux` test and a second test with a specific version to the `darwin` test.

> In case this PR introduced TypeScript/JavaScript code changes:

- [x] I have written test cases for the changes in this pull request
- [x] I have run `npm run format` before the commit.
- [x] I have run `npm run lint` before the commit.
- [x] I have run `npm run release` before the commit.
- [x] `npm test` returns with no unit test errors and all code covered.

Note: running these scripts, automatically added two unrelated changes to the PR, which I have manually removed (had to disable the `pre-commit` hook to do so). The changes were to `package-lock.json` and to `dist/index.js`. Not sure what's going on there.

> In case this PR edits any scripts:

- [ ] I have checked the edited scripts for syntax.
- [ ] I have tested the changes in an integration test (If yes, provide workflow YAML and link).

### CODE REVIEW

**Review by shivammathur — CHANGES_REQUESTED** [review]
Please remove `dist/index.js.bak` file from the PR.

**Comment by jrfnl** [comment]
Yikes! Sorry about that, not sure how that got in there as I have a git global ignore set up for those type of files... Either way, should be fixed now.

**Review by shivammathur — APPROVED** [review]

**Comment by shivammathur** [comment]
@jrfnl Thanks!

**Comment by jrfnl** [comment]
Thanks @shivammathur !

**Comment by jrfnl** [comment]
Integration test:
* Yaml changes: https://github.com/jrfnl/PHPMailer/commit/342ad9bba5cccee6f581e5f1db1beda03e2c0124
* Successful action run: https://github.com/jrfnl/PHPMailer/actions/runs/1255741429

**Comment by jrfnl** [comment]
FYI: I've added an FAQ section to the README for the PHPUnit Polyfills about how using it via `setup-php` with `tools`:
https://github.com/Yoast/PHPUnit-Polyfills#q-how-do-i-run-my-tests-when-the-library-is-installed-via-the-github-actions-setup-php-action-

**Pull request merged**
